name: Compilar Ejecutables Windows (32-bit & 64-bit)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Descargar el código del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Compilar versión de 32 bits (ia32)
        run: npm run build-32

      - name: Compilar versión de 64 bits (x64)
        run: npm run build-64

      - name: Comprimir carpetas resultantes en ZIP
        run: |
          Compress-Archive -Path build/win32/* -DestinationPath app-windows-32bit.zip
          Compress-Archive -Path build/win64/* -DestinationPath app-windows-64bit.zip

      - name: Subir ejecutables como Artefactos
        uses: actions/upload-artifact@v4
        with:
          name: Ejecutables-Windows
          path: "*.zip"
